# Build Spec for AWS CodeBuild CI

version: 0.2

#env:
  #variables:
     # key: "value"
  #parameter-store:
     # key: "value"

phases:
  install:
    commands:
      apt-get update;
      apt-get install -y curl;
      apt-get install -y libgfortran3;
      apt-get install autoconf automake libtool curl make g++ unzip;
      wget https://github.com/google/protobuf/archive/v3.4.1.zip;
      unzip v3.4.1.zip;
      cd protobuf-3.4.1 && ./autogen.sh && ./configure --prefix=/usr && make && make install && cd ..;
      pip install pip -U;
      pip install retrying;
      pip install mock;
      pip install flask;
      pip install -U mxnet;
      pip install Pillow;
      pip install requests;
      pip install flask-cors;
      pip install fasteners;
      pip install pytest -U;
      pip install jsonschema;
      pip install onnx -U;
      pip install onnx-mxnet -U;
      pip install pylint;
      pip install -U -e .;

  #pre_build:
    #commands:
      # - command

  build:
    commands:
      python -m pytest mms/tests/unit_tests &&
      python -m pytest mms/tests/integration_tests &&
      pylint -rn --rcfile=./mms/tests/pylintrc mms/.

 #post_build:
    #commands:
      # - command

#artifacts:
  #files:
    # - location
  #discard-paths: yes
  #base-directory: location
