# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#     http://www.apache.org/licenses/LICENSE-2.0
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

"""
This file defines all the errors generated by Model Archiving and Export tools
"""


class ModelPackagingErrorCodes(object):
    """
    Class defining all the error codes generated by Model export tool.
    For explanation on each error please visit "docs/model_export_tool_errors"
    """
    # Invalid engine name
    INVALID_ENGINE_NAME = 14000

    # Invalid runtime
    INVALID_RUNTIME_TYPE = 14001

    # Invalid model files
    INVALID_MODEL_FILES = 14002
