FROM nvidia/cuda:9.0-cudnn7-devel

COPY install.sh /

RUN /install.sh && pip install mxnet-cu90 && mkdir /mxnet_model_server

COPY wsgi.py setup_mms.py mxnet-model-server.sh /mxnet_model_server/

ENV PATH="/mxnet_model_server:${PATH}" GPU_IMAGE=1 gpu_id=0

LABEL maintainer="yuruofei@amazon.com, esterhaz@amazon.com, hag@amazon.com"