FROM nvidia/cuda:9.0-cudnn7-devel

COPY install.sh /

RUN /install.sh

RUN pip install mxnet-cu90

ADD mms_docker_gpu mxnet-model-server

ENV PATH="/mxnet-model-server:${PATH}"

LABEL maintainer="yuruofei@amazon.com, esterhaz@amazon.com, hag@amazon.com"