# Build Spec for AWS CodeBuild CI

version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y curl
      - pip install pip -U
      - pip install future
      - pip install Pillow
      - pip install pytest
      - pip install wheel
      - pip install twine
      - pip install pytest-mock -U
      - pip install -U -e .[mxnet]

  pre_build:
    commands:
        - $NIGHTLYBRANCH
            
  build:
    commands:
      - frontend/gradlew -p frontend build
      - python -m pytest mms/tests/unit_tests
      - python -m pytest model_archiver/tests/unit_tests
      # integration test is broken: https://github.com/awslabs/mxnet-model-server/issues/437
      #- python -m pytest mms/tests/integration_tests
      - pylint -rn --rcfile=./mms/tests/pylintrc mms/.
      - pylint -rn --rcfile=./model_archiver/tests/pylintrc model_archiver/.
      - $NIGHTLYBUILD
      - eval $NIGHTLYUPLOAD

# local build will hang without artifacts section
artifacts:
  files:
    - dist/*.whl
