# Build Spec for AWS CodeBuild CI - Nightly

version: 0.2

phases:
  build:
    commands:
      # create and install build
      - ci/scripts/linux_build.sh
      - pip install dist/*
      # modelarchiver tests
      - ci/scripts/linux_test_modelarchiver.sh
      # run python tests
      - ci/scripts/linux_test_python.sh
      # run api tests
      - ci/scripts/linux_test_api.sh management
      - ci/scripts/linux_test_api.sh inference
      - ci/scripts/linux_test_api.sh https

  post_build:
    commands:
      - mkdir -p nightly_artifacts/build_artifacts; mkdir -p nightly_artifacts/model_archiver_tests;
      - mkdir -p nightly_artifacts/mms_python_units;   mkdir -p nightly_artifacts/api_tests
      - mv frontend/server/build/reports/tests/test/* nightly_artifacts/build_artifacts
      - mv model-archiver/result_units/* nightly_artifacts/model_archiver_tests
      - mv result_units/* nightly_artifacts/mms_python_units
      - mv tests/api/artifacts/* nightly_artifacts/api_tests


artifacts:
    files:
      - '**/*'
    name: MMS-NIGHTLY-$(date +%Y-%m-%d)
    base-directory: nightly_artifacts
