# Build Spec for AWS CodeBuild CI - SMOKE

version: 0.2

phases:
  build:
    commands:
      # create and install build
      - ./.circleci/scripts/linux_build.sh
      - pip install dist/*
      # modelarchiver tests
      - ./.circleci/scripts/linux_test_modelarchiver.sh
      # run python tests
      - .circleci/scripts/linux_test_python.sh

artifacts:
  files:
    - frontend/server/build/reports/tests/test/**/*
    - model-archiver/results_units/**/*
    - htmlcov/**/*


