# Build Spec for AWS CodeBuild CI - Nightly

version: 0.2

phases:
  build:
    commands:
      # create and install build
      - ./.circleci/scripts/linux_build.sh
      - pip install dist/*
      # modelarchiver tests
      - ./.circleci/scripts/linux_test_modelarchiver.sh
      # run python tests
      - .circleci/scripts/linux_test_python.sh
      # run api tests
      - ./.circleci/scripts/linux_test_api.sh management
      - ./.circleci/scripts/linux_test_api.sh inference
      - ./.circleci/scripts/linux_test_api.sh https

artifacts:
  files:
    - frontend/server/build/reports/tests/test/**/*
    - model-archiver/results_units/**/*
    - test/management-api-report.html
    - test/inference-api-report.html
    - test/https-api-report.html
    - htmlcov/**/*
  name: MMS-NIGHTLY-$(date +%Y-%m-%d)



